name: Deploy to dev server

on:
  push:
    branches:
      - hack_2022

jobs:
  surge-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install surge
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install -g surge
      - run: surge ./ ${{secrets.SURGE_HACK7_DOMAIN}} --token ${{secrets.SURGE_TOKEN}}